---
- hosts: all
#- hosts: u18
  become: yes
  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  roles:

  tasks:
    - name: Ensure group ubuntu exists
      group:
        name: ubuntu
        state: present
    - name: Add user ubuntu
      user:
        name: ubuntu
        groups: ubuntu,root
        append: yes
    - name: change owner
      file:
        path: '{{ docroot }}'
        owner: ubuntu
        group: ubuntu
        recurse: yes

