---
- hosts: u18
  become: yes
  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  roles:

  tasks:
    - name: Install php modules
      apt:
        name:
          - php{{ php_version }}-zip

