---
- hosts: u18
  become: yes
  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  roles:
   - geerlingguy.php-versions
   - geerlingguy.php

  tasks:
   - name: Update all packages to the latest version
     apt:
      name: aptitude
      state: present
   - name: Update APT Cache
     become: yes
     become_user: root
     apt:
      update_cache: yes
      cache_valid_time: 1800
     register: apt_result
     until: apt_result is successful
     retries: 3
     delay: 1
     ignore_errors: yes
   - name: Install git
     apt:
       name: git
       state: present
       update_cache: no
   - git:
       repo: 'https://github.com/brian3t/fansconnectapp_api.git'
       dest: /var/www/lnoapi
