---
- hosts: u18
  vars:

  roles:
   - weareinteractive.sudo
   - { role: manala.vim }
   - weareinteractive.openssl
   - geerlingguy.composer

  tasks:
   - name: Update all packages to the latest version
     apt:
      name: aptitude
      state: present
   - name: Update APT Cache
     become: yes
     become_user: root
     apt:
      update_cache: yes
      cache_valid_time: 1800
     register: apt_result
     until: apt_result is successful
     retries: 3
     delay: 1
     ignore_errors: yes
   - name: Install lsb-release
     become: yes
     become_user: root
     apt:
       name: lsb-release
   - name: Install some apts
     become: yes
     apt:
       name:
        - telnet
        - rsync

