---
- hosts: all
  vars_files:
    - vars/main.yml

  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  roles:
   - role: morgangraphics.ansible_role_nvm
     nvm_commands:
       - "nvm exec default npm install"
     become: true            # THIS WILL CHANGE THE LOGIN CONTEXT TO USE THE USER BELOW
     become_user: ubuntu   # THIS INSTALLS NVM IN THE CONTEXT OF THE EC2-USER/DEFAULT USER

  tasks:


