---
- hosts: all
  become: yes
  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  tasks:
   - name: Update all packages to the latest version
     apt:
      name: aptitude
      state: present
   - name: Update APT Cache
     become: yes
     become_user: root
     apt:
      update_cache: yes
      cache_valid_time: 1800
     register: apt_result
     until: apt_result is successful
     retries: 3
     delay: 1
     ignore_errors: yes
   - name: copy file to remote server_including git config
     synchronize:
       src: ./res/lnoapi/
       dest: /
       rsync_opts:
         - --include=*/
   - git:
       repo: 'https://github.com/brian3t/fansconnectapp_api.git'
       dest: /var/www/lnoapi
       force: no
   - name: change owner
     file:
       path: '{{ docroot }}'
       owner: ubuntu
       group: ubuntu
       recurse: yes
   - name: Install php modules
     apt:
       name:
         - php{{ php_version }}-zip
       state: present
       update_cache: no
   - name: Install more php modules
     apt:
       name:
         - php-mysql
         - php{{ php_version }}-mysql
       state: present
       update_cache: no
   - name: Ansible copy file to remote server
     synchronize:
       src: ./lnoapi/
       dest: /var/www/lnoapi/
       rsync_opts:
         - --include=*/
   - name: composer install
     shell: "cd {{ docroot }} && composer install"
   - name: "setup scraper cron"
     cron:
       name: "scrape sdr everyday"
       user: "ubuntu"
       minute: "0"
       hour: "12"
       job: "{{ docroot }}/yii dl/scrape-sdr-all"
