---
- hosts: all
  become: yes
  become_user: ubuntu
  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  tasks:
   - name: copy file to remote server_including git config
     synchronize:
       src: ./res/lnoapi/
       dest: /
       rsync_opts:
         - --include=*/
   - git:
       repo: 'https://github.com/brian3t/fansconnectapp_api.git'
       dest: /var/www/lnoapi
       force: no
    - name: Ansible copy file to remote server
     synchronize:
       src: ./lnoapi/
       dest: /var/www/lnoapi/
       rsync_opts:
         - --include=*/
   - name: composer install
     shell: "cd {{ docroot }} && composer install"
   - name: "setup scraper cron"
     cron:
       name: "scrape sdr everyday"
       user: "ubuntu"
       minute: "0"
       hour: "12"
       job: "{{ docroot }}/yii dl/scrape-sdr-all"
