---
- hosts: all
  vars_files:
   - vars/main.yml
  vars:

  roles:
   - weareinteractive.sudo
   - manala.vim
   - weareinteractive.openssl
   - geerlingguy.apache
   - geerlingguy.php-versions
   - geerlingguy.php
   - geerlingguy.composer

  tasks:
   - name: Update all packages to the latest version
     apt:
      name: aptitude
      state: present
   - name: Update APT Cache
     become: yes
     become_user: root
     apt:
      update_cache: yes
      cache_valid_time: 1800
     register: apt_result
     until: apt_result is successful
     retries: 3
     delay: 1
     ignore_errors: yes
   - name: Install lsb-release
     become: yes
     become_user: root
     apt:
       name: lsb-release
   - name: Install some apts
     become: yes
     apt:
       name:
        - bash
        - telnet
        - rsync
        - cron
        - wget
        - curl
        - build-essential
   - name: Ensure group ubuntu exists
     group:
       name: ubuntu
       state: present
   - name: Add user ubuntu
     user:
       name: "{{ user }}"
       groups: ubuntu,root
       append: yes
       shell: /bin/bash
       home: "/home/{{ user }}"
   - name: Install git
     apt:
       name: git
       state: present
       update_cache: no
 #Apache Configuration
   - name: Install LAMP Packages
     apt: name={{ item }} update_cache=yes state=latest
     loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]

   - name: Install php modules
     apt:
       name:
         - php{{ php_version }}-zip
       state: present
       update_cache: no
   - name: Install more php modules
     apt:
       name:
         - php-curl
         - php-mysql
         - php-mbstring
         - php-xml
         - php-gd
         - php-zip
         - php{{ php_version }}-mysql
       state: present
       update_cache: no
   - name: change owner
     file:
       path: '/var/www'
       owner: ubuntu
       group: ubuntu
       recurse: yes

    # MySQL Configuration
#   - name: Sets the root password
#     mysql_user:
#       name: root
#       password: 'Trapok)1'
#       login_unix_socket: /var/run/mysqld/mysqld.sock
