---
- hosts: u18
  become: yes
  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'

  roles:

  tasks:
    - name: Install more php modules
      apt:
        name:
          - php-mysql
          - php{{ php_version }}-mysql
        state: present
        update_cache: no

