---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.
- hosts: aha
  vars:
      - docroot: /var/www/myservers.com/public
  tasks:
      - name: Add Nginx Repository
        apt_repository: repo='ppa:nginx/stable' state=present
        register: ppastable
      - name: Install Nginx
        apt: pkg=nginx state=present update_cache=true
        when: ppastable|success
        register: nginxinstalled
        notify:
            - Start Nginx
      - name: Create Web Root
        when: nginxinstalled|success
        file: dest={{'{{'}}docroot{{'}}'}} mode=775 state=directory owner=www-data group=www-data
        notify: Reload Nginx
  handlers:
      - name: Start Nginx
        service: name=nginx state=started
      - name: Reload Nginx
        service: name=nginx state=reloaded

#docker exec -t -i aha ls /var/www
-
#      - apt: pkg



#- hosts: mongo_servers
#  roles:
#      - role: mongod
#
#- hosts: mongoc_servers
#  roles:
#      - role: mongoc
#
#- hosts: mongos_servers
#  roles:
#      - role: mongos
#
#- hosts: mongo_servers
#  tasks:
#      - include: roles/mongod/tasks/shards.yml

