# from galaxy
- src: manala.vim
- src: weareinteractive.sudo
- src: geerlingguy.php
- src: geerlingguy.php-versions
- src: weareinteractive.openssl
- src: geerlingguy.composer
- src: geerlingguy.nodejs
- src: morgangraphics.ansible_role_nvm
