---
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml

  vars:
   - docroot: /var/www/lnoapi
   - php_version: '7.3'
  roles:
    - { role: geerlingguy.phpmyadmin }

  tasks:




